name: "lint"
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - name: Install Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'dev-requirements.txt'
    - name: Install Python dependencies
      run: pip install -r dev-requirements.txt
    # - name: Install linters
    #   run: |
    #     sudo apt install shellcheck
    - name: format python files
      run: |
        black --check $(git ls-files "*.py")
    - name: typecheck python files
      run: |
        pyright $(git ls-files "*.py")